### ISSUE TITLE
DMRseq stops after processing a few chromosome

### ISSUE THREAD

**Issue by geethavenk** [kdkorthauer/dmrseq#23]
Hi,

I am running dmrseq on my data which is not so big. I have around 4000 CpG sites from the genes of interest. When I run dmrseq, it processes a few scaffolds and then stops (like below). Can anyone please help me to rectify this. Thanks.

Performing a global test of H0: no difference among 4 groups (assuming the test covariate Location is a factor).
Parallelizing using 38 workers/cores (backend: BiocParallel:MulticoreParam).
Computing on 1 chromosome(s) at a time.

Detecting candidate regions with coefficient larger than 0.05 in magnitude.
...Chromosome scaffold10046: Smoothed (0 min). 1 regions scored (0 min). 
...Chromosome scaffold107110: Smoothed (0 min). 1 regions scored (0.01 min). 
...Chromosome scaffold12945: Smoothed (0 min). 

Thanks,
Geeta

**Comment by kdkorthauer** [comment]
Hi Geeta,

Can you clarify what happens after it stops? Do you see any error messages? Are you sure it's not still computing?

Also, with so few CpG sites, you probably don't need to parallelize the computation with so many workers. I would recommend only using a few cores instead of 38. 

Best,
Keegan

**Comment by geethavenk** [comment]
Hi Keegan,

It just stops and I don't get any error messages. I have let it run for more than 12 hours but still nothing happens. 

Also, I have tried with 6 cores but the issue persists. 

Thank you,
Best,
Geeta

**Comment by kdkorthauer** [comment]
Hi Geeta,

Thank you for the additional details. I haven't seen this happen before, and I'm not sure what could be causing it. 

Would you be able to send me a portion of your data object so that I can diagnose the problem? Just the first few scaffolds (including the one that hangs) should be sufficient. You can send by email if your prefer (keegan@jimmy.harvard.edu).

Best,
Keegan

**Comment by geethavenk** [comment]
Hi Keegan,

I have mailed you the BSseq object. 
Thank you very much.

Best,
Geeta

**Comment by kdkorthauer** [comment]
Hi Geeta,

Thank you for sending the data via email. I was able to run dmrseq on it, and it did not hang at any point.

Which version of dmrseq are you using? Can you please verify that you don't have any out of date packages with `BiocManager::valid()`? If so, please try updating and see if the problem still occurs.

Best,
Keegan

**Comment by geethavenk** [comment]
Hi Keegan,

Thank you very much. I will update the out dated packages and check.

Best,
Geeta

**Comment by geethavenk** [comment]
Hi Keegan,
I updated the outdated packages and its working now. Thank you very much.

Best,
Geeta

**Comment by kdkorthauer** [comment]
Hi Geeta,

Great!

Best,
Keegan
