### ISSUE TITLE
How to interpret beta and stat?

### ISSUE THREAD

**Issue by bishwaG** [kdkorthauer/dmrseq#28]
Hi,
In simple two group analysis I get methylation difference which is easy to interpret. Now, I am doing differential methylation analysis by adjusting a co-variate. The result of the analysis has beta and stat. It might be a stupid question for you but, I am not getting a clue how to interpret values on beta and stat columns in terms of group difference. Your answer will be highly valuable to me :)

**Comment by kdkorthauer** [comment]
Hi,

Thanks for your question. First, I'll point out that regardless of whether you are performing a two-group comparison or also adjusting for covariates, the results output includes both the beta coefficient estimate and a statistic. The beta coefficient estimate is the result of the GLS model fit, so it is the estimate of the effect on arcsine-transformed methylation proportions due to the test covariate. The statistic is the Wald test statistic that corresponds to this beta coefficient. This is explained in the [dmrseq vignette](https://bioconductor.org/packages/release/bioc/vignettes/dmrseq/inst/doc/dmrseq.html#41_output_of_dmrseq). 

You can also obtain estimates of the mean methylation proportion difference due to the test covariate using the `meanDiff()` function, which is also explained in the [dmrseq vignette](https://bioconductor.org/packages/release/bioc/vignettes/dmrseq/inst/doc/dmrseq.html#56_extract_raw_mean_methylation_differences).

Hope that helps!

Best,
Keegan

**Comment by bishwaG** [comment]
Hi,
Thank you for your answer. I still have some queries in my mind. Lets say beta_GroupA is 0.6 and beta_GroupB is -0.25. Does it mean that GroupA has positive effect on a DMR and GroupB has negative effect on a DMR?

I have five groups (one of them is a control) in my analysis, but I got beta values 4 group (also mentioned in vignette). Is there any way to interpret the effect of the control group?

Does it mean that if stat value is close to zero there is no evidence for methylation difference among groups?

**Comment by kdkorthauer** [comment]
Hi @bishwaG,

The coefficient estimates for each group are relative to the reference group. This means that if beta_GroupA is 0.6, then Group A has higher methylation than the reference group. If beta_GroupB is -0.25, then Group B has lower methylation than the reference category. The reference group is the one that does not have it's own beta coefficient. 

Yes, if the statistic is close to zero, there is not much evidence for methylation difference among the groups. 

Hope that helps!

Best,
Keegan

**Comment by bishwaG** [comment]
Hi @kdkorthauer 
Thanks a lot! That helped super much :)

**Comment by zyqfrog10** [comment]
Hi @kdkorthauer,

Sorry for asking a similar question on 'beta' in a closed thread.
'area' is the sum of the smoothed beta values. From this definition, I would think the beta value is for individual CpGs and 'area' is the sum of smoothed beta values in each region. Then how should I interpret 'beta' reported along side 'area'? Is it the mean of beta?

Thank you,
Ying

**Comment by kdkorthauer** [comment]
Hi @zyqfrog10,

Great question!

There are two different usages of the term 'beta' (they are related, but require some more technical details to understand the differences):

1. beta **value**: CpG methylation level (proportion); it is common in methylation literature to refer to the methylation difference estimate for a single CpG as the beta value. In dmrseq, the area is the sum of the *smoothed (and scaled) estimates for methylation differences over all CpGs in a region*. For more than two group comparisons, the value used is the max difference between any two groups. 

2. beta **coefficient**: the estimate of effect size of methylation difference across a region from a GLS model fit to raw methylation values. Intuitively, it represents something like the average beta value, but these are not equivalent here due to how differently these quantities are estimated. A simple averaging of beta values, for example, will not adjust for inter-CpG correlation or variability by coverage. 

I hope that helps!

Best,
Keegan

**Comment by zyqfrog10** [comment]
Hi @kdkorthauer ,

Thank you for your explanation! That helps a lot.

So the 'area' is based on the 'beta value' over all CpGs in a region while the 'beta' is actually 'beta coefficient'.  As commonly defined, 'beta value' is the CpG methylation level. In your description, the methylation difference should be in fact the beta value difference (by subtraction), right?  

Thanks,
YZ

**Comment by kdkorthauer** [comment]
Hi YZ,

Yes, the beta value is the proportion *difference*. Apologies for leaving that out of my previous description. And what you write is correct, with the exception that the beta values used to compute the area in dmrseq are also smoothed and scaled (as I described in my previous message).

Best,
Keegan

**Comment by zyqfrog10** [comment]
Wonderful, @kdkorthauer 
Thank you very much for your quick response. It's all clear.
