### ISSUE TITLE
distribution of coverage 

### ISSUE THREAD

**Issue by priyatamapandey** [kdkorthauer/dmrseq#40]
Hi ,
I am using plotEmpiricalDistribution function and it did not generate all the curves for my all the samples.
I am attaching the graph here. You can see here it plotted only three curves for the second group and did not plot the distribution from D3 to D9 samples. 

<img width="484" alt="Screen Shot 2020-05-02 at 2 47 06 PM" src="https://user-images.githubusercontent.com/17990280/80893074-f65b3b80-8c83-11ea-9200-4cce5c253997.png">

Also, Can I plot the sample wise methylation distribution too? As the above one is for the coverage.

Thank you for any help,
Priya

**Comment by kdkorthauer** [comment]
Hi Priya,

I apologize that I somehow overlooked this open issue. 

The missing lines were due to a limitation on the number of unique line types available - I have just pushed a fix that will plot all samples as the same line type if there are more samples than the number of line types. Apologies for the delay. 

For your second question - yes, the default `type="M"` will plot the methylation values.
