### ISSUE TITLE
Is it possible to output the smooth methylation estimates from dmrseq?

### ISSUE THREAD

**Issue by seifudd** [kdkorthauer/dmrseq#46]
Hi,

Is it possible to output the smooth methylation estimates from dmrseq? Since dmrseq does the smoothing differently from Bsmooth() and there is no function to separately smooth the raw methylation estimates, I was wondering how to get these as a separate output? Thank you for your help.

Thanks, Fayaz

**Comment by seifudd** [comment]
I just realized that dmrseq smooths the methylation differences rather than the estimates themselves. Is it possible to get the smooth methylation differences as an output?

**Comment by kdkorthauer** [comment]
It is currently not possible to output smoothed methylation estimates. As these are only used to detect candidate regions, and not in the estimate of methylation differences, they are not used in the same way as in Bsmooth either.

**Comment by kaanokay** [comment]
Dear @kdkorthauer,

Thank you for developing this nice package.

I'm wondering whether if its now possible to get smoothed BSseq object from dmrseq pipeline? As you mentioned, way to smooth data in bsseq and dmrseq are different. I want to compare both in terms of smoothed values.

All the best.

**Comment by kdkorthauer** [comment]
Hi @kaanokay, 

Thanks for reaching out. Direct output of the intermediate smoothed methylation levels has not been implemented. I will emphasize that these smoothed values are intermediate, in that they are only considered in the initial phase of the algorithm (that is, to identify candidate regions). All subsequent modeling and statistics are carried out on the original observed (unsmoothed) methylation levels. Since I don't see a strong argument for the average user to need these values, I am not able to allocate resources to implement such a feature. However, other contributors are welcome to either submit pull requests implementing such a feature in the package for me to review, or to use and modify the provided open source code on their own to save these intermediate values. It is the `beta` that is computed [here](https://github.com/kdkorthauer/dmrseq/blob/5f0b0ab53e3264c51cd5510a3bbf759e0ed6bf57/R/helper_functions.R#L277) that contains the intermediate smoothed values (that line is within a for loop that iterates over chromosomes). 

Hope that helps!

**Comment by kaanokay** [comment]
@kdkorthauer,

Thank you so much for explanation, I'll check scripts that you mentioned above.

Kind regards.
